name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.0
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_app_name: dictionarydb
          heroku_api_key: "${{ secrets.HEROKU_API_KEY }}"
          heroku_email: "${{ secrets.HEROKU_EMAIL }}"
          usedocker: true
          healthcheck: "https://dictionarydb.herokuapp.com/health"
          delay: 30
          rollbackonhealthcheckfailed: true
        env:
          HD_DICTIONARYDB_API_TRUST_PROXY_IPS: "*"
